<?php
/**
 * Dial-code country list for Chat Quote for WooCommerce.
 *
 * Auto-generated comprehensive list of all world countries and dial codes.
 *
 * @package ChatQuoteForWooCommerce
 */

defined( 'ABSPATH' ) || exit;

return array(
	array( 'iso' => 'AF', 'name' => 'Afghanistan', 'dial' => '93', 'flag' => '🇦🇫' ),
	array( 'iso' => 'AL', 'name' => 'Albania', 'dial' => '355', 'flag' => '🇦🇱' ),
	array( 'iso' => 'DZ', 'name' => 'Algeria', 'dial' => '213', 'flag' => '🇩🇿' ),
	array( 'iso' => 'AS', 'name' => 'American Samoa', 'dial' => '1684', 'flag' => '🇦🇸' ),
	array( 'iso' => 'AD', 'name' => 'Andorra', 'dial' => '376', 'flag' => '🇦🇩' ),
	array( 'iso' => 'AO', 'name' => 'Angola', 'dial' => '244', 'flag' => '🇦🇴' ),
	array( 'iso' => 'AI', 'name' => 'Anguilla', 'dial' => '1264', 'flag' => '🇦🇮' ),
	array( 'iso' => 'AG', 'name' => 'Antigua and Barbuda', 'dial' => '1268', 'flag' => '🇦🇬' ),
	array( 'iso' => 'AR', 'name' => 'Argentina', 'dial' => '54', 'flag' => '🇦🇷' ),
	array( 'iso' => 'AM', 'name' => 'Armenia', 'dial' => '374', 'flag' => '🇦🇲' ),
	array( 'iso' => 'AW', 'name' => 'Aruba', 'dial' => '297', 'flag' => '🇦🇼' ),
	array( 'iso' => 'AU', 'name' => 'Australia', 'dial' => '61', 'flag' => '🇦🇺' ),
	array( 'iso' => 'AT', 'name' => 'Austria', 'dial' => '43', 'flag' => '🇦🇹' ),
	array( 'iso' => 'AZ', 'name' => 'Azerbaijan', 'dial' => '994', 'flag' => '🇦🇿' ),
	array( 'iso' => 'BS', 'name' => 'Bahamas', 'dial' => '1242', 'flag' => '🇧🇸' ),
	array( 'iso' => 'BH', 'name' => 'Bahrain', 'dial' => '973', 'flag' => '🇧🇭' ),
	array( 'iso' => 'BD', 'name' => 'Bangladesh', 'dial' => '880', 'flag' => '🇧🇩' ),
	array( 'iso' => 'BB', 'name' => 'Barbados', 'dial' => '1246', 'flag' => '🇧🇧' ),
	array( 'iso' => 'BY', 'name' => 'Belarus', 'dial' => '375', 'flag' => '🇧🇾' ),
	array( 'iso' => 'PW', 'name' => 'Belau', 'dial' => '680', 'flag' => '🇵🇼' ),
	array( 'iso' => 'BE', 'name' => 'Belgium', 'dial' => '32', 'flag' => '🇧🇪' ),
	array( 'iso' => 'BZ', 'name' => 'Belize', 'dial' => '501', 'flag' => '🇧🇿' ),
	array( 'iso' => 'BJ', 'name' => 'Benin', 'dial' => '229', 'flag' => '🇧🇯' ),
	array( 'iso' => 'BM', 'name' => 'Bermuda', 'dial' => '1441', 'flag' => '🇧🇲' ),
	array( 'iso' => 'BT', 'name' => 'Bhutan', 'dial' => '975', 'flag' => '🇧🇹' ),
	array( 'iso' => 'BO', 'name' => 'Bolivia', 'dial' => '591', 'flag' => '🇧🇴' ),
	array( 'iso' => 'BQ', 'name' => 'Bonaire, Saint Eustatius and Saba', 'dial' => '599', 'flag' => '🇧🇶' ),
	array( 'iso' => 'BA', 'name' => 'Bosnia and Herzegovina', 'dial' => '387', 'flag' => '🇧🇦' ),
	array( 'iso' => 'BW', 'name' => 'Botswana', 'dial' => '267', 'flag' => '🇧🇼' ),
	array( 'iso' => 'BR', 'name' => 'Brazil', 'dial' => '55', 'flag' => '🇧🇷' ),
	array( 'iso' => 'IO', 'name' => 'British Indian Ocean Territory', 'dial' => '246', 'flag' => '🇮🇴' ),
	array( 'iso' => 'BN', 'name' => 'Brunei', 'dial' => '673', 'flag' => '🇧🇳' ),
	array( 'iso' => 'BG', 'name' => 'Bulgaria', 'dial' => '359', 'flag' => '🇧🇬' ),
	array( 'iso' => 'BF', 'name' => 'Burkina Faso', 'dial' => '226', 'flag' => '🇧🇫' ),
	array( 'iso' => 'BI', 'name' => 'Burundi', 'dial' => '257', 'flag' => '🇧🇮' ),
	array( 'iso' => 'KH', 'name' => 'Cambodia', 'dial' => '855', 'flag' => '🇰🇭' ),
	array( 'iso' => 'CM', 'name' => 'Cameroon', 'dial' => '237', 'flag' => '🇨🇲' ),
	array( 'iso' => 'CA', 'name' => 'Canada', 'dial' => '1', 'flag' => '🇨🇦' ),
	array( 'iso' => 'CV', 'name' => 'Cape Verde', 'dial' => '238', 'flag' => '🇨🇻' ),
	array( 'iso' => 'KY', 'name' => 'Cayman Islands', 'dial' => '1345', 'flag' => '🇰🇾' ),
	array( 'iso' => 'CF', 'name' => 'Central African Republic', 'dial' => '236', 'flag' => '🇨🇫' ),
	array( 'iso' => 'TD', 'name' => 'Chad', 'dial' => '235', 'flag' => '🇹🇩' ),
	array( 'iso' => 'CL', 'name' => 'Chile', 'dial' => '56', 'flag' => '🇨🇱' ),
	array( 'iso' => 'CN', 'name' => 'China', 'dial' => '86', 'flag' => '🇨🇳' ),
	array( 'iso' => 'CX', 'name' => 'Christmas Island', 'dial' => '61', 'flag' => '🇨🇽' ),
	array( 'iso' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'dial' => '61', 'flag' => '🇨🇨' ),
	array( 'iso' => 'CO', 'name' => 'Colombia', 'dial' => '57', 'flag' => '🇨🇴' ),
	array( 'iso' => 'KM', 'name' => 'Comoros', 'dial' => '269', 'flag' => '🇰🇲' ),
	array( 'iso' => 'CG', 'name' => 'Congo (Brazzaville)', 'dial' => '242', 'flag' => '🇨🇬' ),
	array( 'iso' => 'CD', 'name' => 'Congo (Kinshasa)', 'dial' => '243', 'flag' => '🇨🇩' ),
	array( 'iso' => 'CK', 'name' => 'Cook Islands', 'dial' => '682', 'flag' => '🇨🇰' ),
	array( 'iso' => 'CR', 'name' => 'Costa Rica', 'dial' => '506', 'flag' => '🇨🇷' ),
	array( 'iso' => 'HR', 'name' => 'Croatia', 'dial' => '385', 'flag' => '🇭🇷' ),
	array( 'iso' => 'CU', 'name' => 'Cuba', 'dial' => '53', 'flag' => '🇨🇺' ),
	array( 'iso' => 'CW', 'name' => 'Curaçao', 'dial' => '599', 'flag' => '🇨🇼' ),
	array( 'iso' => 'CY', 'name' => 'Cyprus', 'dial' => '357', 'flag' => '🇨🇾' ),
	array( 'iso' => 'CZ', 'name' => 'Czech Republic', 'dial' => '420', 'flag' => '🇨🇿' ),
	array( 'iso' => 'DK', 'name' => 'Denmark', 'dial' => '45', 'flag' => '🇩🇰' ),
	array( 'iso' => 'DJ', 'name' => 'Djibouti', 'dial' => '253', 'flag' => '🇩🇯' ),
	array( 'iso' => 'DM', 'name' => 'Dominica', 'dial' => '1767', 'flag' => '🇩🇲' ),
	array( 'iso' => 'DO', 'name' => 'Dominican Republic', 'dial' => '1809', 'flag' => '🇩🇴' ),
	array( 'iso' => 'EC', 'name' => 'Ecuador', 'dial' => '593', 'flag' => '🇪🇨' ),
	array( 'iso' => 'EG', 'name' => 'Egypt', 'dial' => '20', 'flag' => '🇪🇬' ),
	array( 'iso' => 'SV', 'name' => 'El Salvador', 'dial' => '503', 'flag' => '🇸🇻' ),
	array( 'iso' => 'GQ', 'name' => 'Equatorial Guinea', 'dial' => '240', 'flag' => '🇬🇶' ),
	array( 'iso' => 'ER', 'name' => 'Eritrea', 'dial' => '291', 'flag' => '🇪🇷' ),
	array( 'iso' => 'EE', 'name' => 'Estonia', 'dial' => '372', 'flag' => '🇪🇪' ),
	array( 'iso' => 'SZ', 'name' => 'Eswatini', 'dial' => '268', 'flag' => '🇸🇿' ),
	array( 'iso' => 'ET', 'name' => 'Ethiopia', 'dial' => '251', 'flag' => '🇪🇹' ),
	array( 'iso' => 'FK', 'name' => 'Falkland Islands', 'dial' => '500', 'flag' => '🇫🇰' ),
	array( 'iso' => 'FO', 'name' => 'Faroe Islands', 'dial' => '298', 'flag' => '🇫🇴' ),
	array( 'iso' => 'FJ', 'name' => 'Fiji', 'dial' => '679', 'flag' => '🇫🇯' ),
	array( 'iso' => 'FI', 'name' => 'Finland', 'dial' => '358', 'flag' => '🇫🇮' ),
	array( 'iso' => 'FR', 'name' => 'France', 'dial' => '33', 'flag' => '🇫🇷' ),
	array( 'iso' => 'GF', 'name' => 'French Guiana', 'dial' => '594', 'flag' => '🇬🇫' ),
	array( 'iso' => 'PF', 'name' => 'French Polynesia', 'dial' => '689', 'flag' => '🇵🇫' ),
	array( 'iso' => 'GA', 'name' => 'Gabon', 'dial' => '241', 'flag' => '🇬🇦' ),
	array( 'iso' => 'GM', 'name' => 'Gambia', 'dial' => '220', 'flag' => '🇬🇲' ),
	array( 'iso' => 'GE', 'name' => 'Georgia', 'dial' => '995', 'flag' => '🇬🇪' ),
	array( 'iso' => 'DE', 'name' => 'Germany', 'dial' => '49', 'flag' => '🇩🇪' ),
	array( 'iso' => 'GH', 'name' => 'Ghana', 'dial' => '233', 'flag' => '🇬🇭' ),
	array( 'iso' => 'GI', 'name' => 'Gibraltar', 'dial' => '350', 'flag' => '🇬🇮' ),
	array( 'iso' => 'GR', 'name' => 'Greece', 'dial' => '30', 'flag' => '🇬🇷' ),
	array( 'iso' => 'GL', 'name' => 'Greenland', 'dial' => '299', 'flag' => '🇬🇱' ),
	array( 'iso' => 'GD', 'name' => 'Grenada', 'dial' => '1473', 'flag' => '🇬🇩' ),
	array( 'iso' => 'GP', 'name' => 'Guadeloupe', 'dial' => '590', 'flag' => '🇬🇵' ),
	array( 'iso' => 'GU', 'name' => 'Guam', 'dial' => '1671', 'flag' => '🇬🇺' ),
	array( 'iso' => 'GT', 'name' => 'Guatemala', 'dial' => '502', 'flag' => '🇬🇹' ),
	array( 'iso' => 'GG', 'name' => 'Guernsey', 'dial' => '441481', 'flag' => '🇬🇬' ),
	array( 'iso' => 'GN', 'name' => 'Guinea', 'dial' => '224', 'flag' => '🇬🇳' ),
	array( 'iso' => 'GW', 'name' => 'Guinea-Bissau', 'dial' => '245', 'flag' => '🇬🇼' ),
	array( 'iso' => 'GY', 'name' => 'Guyana', 'dial' => '592', 'flag' => '🇬🇾' ),
	array( 'iso' => 'HT', 'name' => 'Haiti', 'dial' => '509', 'flag' => '🇭🇹' ),
	array( 'iso' => 'HN', 'name' => 'Honduras', 'dial' => '504', 'flag' => '🇭🇳' ),
	array( 'iso' => 'HK', 'name' => 'Hong Kong', 'dial' => '852', 'flag' => '🇭🇰' ),
	array( 'iso' => 'HU', 'name' => 'Hungary', 'dial' => '36', 'flag' => '🇭🇺' ),
	array( 'iso' => 'IS', 'name' => 'Iceland', 'dial' => '354', 'flag' => '🇮🇸' ),
	array( 'iso' => 'IN', 'name' => 'India', 'dial' => '91', 'flag' => '🇮🇳' ),
	array( 'iso' => 'ID', 'name' => 'Indonesia', 'dial' => '62', 'flag' => '🇮🇩' ),
	array( 'iso' => 'IR', 'name' => 'Iran', 'dial' => '98', 'flag' => '🇮🇷' ),
	array( 'iso' => 'IQ', 'name' => 'Iraq', 'dial' => '964', 'flag' => '🇮🇶' ),
	array( 'iso' => 'IE', 'name' => 'Ireland', 'dial' => '353', 'flag' => '🇮🇪' ),
	array( 'iso' => 'IM', 'name' => 'Isle of Man', 'dial' => '441624', 'flag' => '🇮🇲' ),
	array( 'iso' => 'IL', 'name' => 'Israel', 'dial' => '972', 'flag' => '🇮🇱' ),
	array( 'iso' => 'IT', 'name' => 'Italy', 'dial' => '39', 'flag' => '🇮🇹' ),
	array( 'iso' => 'CI', 'name' => 'Ivory Coast', 'dial' => '225', 'flag' => '🇨🇮' ),
	array( 'iso' => 'JM', 'name' => 'Jamaica', 'dial' => '1876', 'flag' => '🇯🇲' ),
	array( 'iso' => 'JP', 'name' => 'Japan', 'dial' => '81', 'flag' => '🇯🇵' ),
	array( 'iso' => 'JE', 'name' => 'Jersey', 'dial' => '441534', 'flag' => '🇯🇪' ),
	array( 'iso' => 'JO', 'name' => 'Jordan', 'dial' => '962', 'flag' => '🇯🇴' ),
	array( 'iso' => 'KZ', 'name' => 'Kazakhstan', 'dial' => '7', 'flag' => '🇰🇿' ),
	array( 'iso' => 'KE', 'name' => 'Kenya', 'dial' => '254', 'flag' => '🇰🇪' ),
	array( 'iso' => 'KI', 'name' => 'Kiribati', 'dial' => '686', 'flag' => '🇰🇮' ),
	array( 'iso' => 'XK', 'name' => 'Kosovo', 'dial' => '383', 'flag' => '🇽🇰' ),
	array( 'iso' => 'KW', 'name' => 'Kuwait', 'dial' => '965', 'flag' => '🇰🇼' ),
	array( 'iso' => 'KG', 'name' => 'Kyrgyzstan', 'dial' => '996', 'flag' => '🇰🇬' ),
	array( 'iso' => 'LA', 'name' => 'Laos', 'dial' => '856', 'flag' => '🇱🇦' ),
	array( 'iso' => 'LV', 'name' => 'Latvia', 'dial' => '371', 'flag' => '🇱🇻' ),
	array( 'iso' => 'LB', 'name' => 'Lebanon', 'dial' => '961', 'flag' => '🇱🇧' ),
	array( 'iso' => 'LS', 'name' => 'Lesotho', 'dial' => '266', 'flag' => '🇱🇸' ),
	array( 'iso' => 'LR', 'name' => 'Liberia', 'dial' => '231', 'flag' => '🇱🇷' ),
	array( 'iso' => 'LY', 'name' => 'Libya', 'dial' => '218', 'flag' => '🇱🇾' ),
	array( 'iso' => 'LI', 'name' => 'Liechtenstein', 'dial' => '423', 'flag' => '🇱🇮' ),
	array( 'iso' => 'LT', 'name' => 'Lithuania', 'dial' => '370', 'flag' => '🇱🇹' ),
	array( 'iso' => 'LU', 'name' => 'Luxembourg', 'dial' => '352', 'flag' => '🇱🇺' ),
	array( 'iso' => 'MO', 'name' => 'Macao', 'dial' => '853', 'flag' => '🇲🇴' ),
	array( 'iso' => 'MG', 'name' => 'Madagascar', 'dial' => '261', 'flag' => '🇲🇬' ),
	array( 'iso' => 'MW', 'name' => 'Malawi', 'dial' => '265', 'flag' => '🇲🇼' ),
	array( 'iso' => 'MY', 'name' => 'Malaysia', 'dial' => '60', 'flag' => '🇲🇾' ),
	array( 'iso' => 'MV', 'name' => 'Maldives', 'dial' => '960', 'flag' => '🇲🇻' ),
	array( 'iso' => 'ML', 'name' => 'Mali', 'dial' => '223', 'flag' => '🇲🇱' ),
	array( 'iso' => 'MT', 'name' => 'Malta', 'dial' => '356', 'flag' => '🇲🇹' ),
	array( 'iso' => 'MH', 'name' => 'Marshall Islands', 'dial' => '692', 'flag' => '🇲🇭' ),
	array( 'iso' => 'MQ', 'name' => 'Martinique', 'dial' => '596', 'flag' => '🇲🇶' ),
	array( 'iso' => 'MR', 'name' => 'Mauritania', 'dial' => '222', 'flag' => '🇲🇷' ),
	array( 'iso' => 'MU', 'name' => 'Mauritius', 'dial' => '230', 'flag' => '🇲🇺' ),
	array( 'iso' => 'YT', 'name' => 'Mayotte', 'dial' => '262', 'flag' => '🇾🇹' ),
	array( 'iso' => 'MX', 'name' => 'Mexico', 'dial' => '52', 'flag' => '🇲🇽' ),
	array( 'iso' => 'FM', 'name' => 'Micronesia', 'dial' => '691', 'flag' => '🇫🇲' ),
	array( 'iso' => 'MD', 'name' => 'Moldova', 'dial' => '373', 'flag' => '🇲🇩' ),
	array( 'iso' => 'MC', 'name' => 'Monaco', 'dial' => '377', 'flag' => '🇲🇨' ),
	array( 'iso' => 'MN', 'name' => 'Mongolia', 'dial' => '976', 'flag' => '🇲🇳' ),
	array( 'iso' => 'ME', 'name' => 'Montenegro', 'dial' => '382', 'flag' => '🇲🇪' ),
	array( 'iso' => 'MS', 'name' => 'Montserrat', 'dial' => '1664', 'flag' => '🇲🇸' ),
	array( 'iso' => 'MA', 'name' => 'Morocco', 'dial' => '212', 'flag' => '🇲🇦' ),
	array( 'iso' => 'MZ', 'name' => 'Mozambique', 'dial' => '258', 'flag' => '🇲🇿' ),
	array( 'iso' => 'MM', 'name' => 'Myanmar', 'dial' => '95', 'flag' => '🇲🇲' ),
	array( 'iso' => 'NA', 'name' => 'Namibia', 'dial' => '264', 'flag' => '🇳🇦' ),
	array( 'iso' => 'NR', 'name' => 'Nauru', 'dial' => '674', 'flag' => '🇳🇷' ),
	array( 'iso' => 'NP', 'name' => 'Nepal', 'dial' => '977', 'flag' => '🇳🇵' ),
	array( 'iso' => 'NL', 'name' => 'Netherlands', 'dial' => '31', 'flag' => '🇳🇱' ),
	array( 'iso' => 'NC', 'name' => 'New Caledonia', 'dial' => '687', 'flag' => '🇳🇨' ),
	array( 'iso' => 'NZ', 'name' => 'New Zealand', 'dial' => '64', 'flag' => '🇳🇿' ),
	array( 'iso' => 'NI', 'name' => 'Nicaragua', 'dial' => '505', 'flag' => '🇳🇮' ),
	array( 'iso' => 'NE', 'name' => 'Niger', 'dial' => '227', 'flag' => '🇳🇪' ),
	array( 'iso' => 'NG', 'name' => 'Nigeria', 'dial' => '234', 'flag' => '🇳🇬' ),
	array( 'iso' => 'NU', 'name' => 'Niue', 'dial' => '683', 'flag' => '🇳🇺' ),
	array( 'iso' => 'NF', 'name' => 'Norfolk Island', 'dial' => '672', 'flag' => '🇳🇫' ),
	array( 'iso' => 'KP', 'name' => 'North Korea', 'dial' => '850', 'flag' => '🇰🇵' ),
	array( 'iso' => 'MK', 'name' => 'North Macedonia', 'dial' => '389', 'flag' => '🇲🇰' ),
	array( 'iso' => 'MP', 'name' => 'Northern Mariana Islands', 'dial' => '1670', 'flag' => '🇲🇵' ),
	array( 'iso' => 'NO', 'name' => 'Norway', 'dial' => '47', 'flag' => '🇳🇴' ),
	array( 'iso' => 'OM', 'name' => 'Oman', 'dial' => '968', 'flag' => '🇴🇲' ),
	array( 'iso' => 'PK', 'name' => 'Pakistan', 'dial' => '92', 'flag' => '🇵🇰' ),
	array( 'iso' => 'PS', 'name' => 'Palestinian Territory', 'dial' => '970', 'flag' => '🇵🇸' ),
	array( 'iso' => 'PA', 'name' => 'Panama', 'dial' => '507', 'flag' => '🇵🇦' ),
	array( 'iso' => 'PG', 'name' => 'Papua New Guinea', 'dial' => '675', 'flag' => '🇵🇬' ),
	array( 'iso' => 'PY', 'name' => 'Paraguay', 'dial' => '595', 'flag' => '🇵🇾' ),
	array( 'iso' => 'PE', 'name' => 'Peru', 'dial' => '51', 'flag' => '🇵🇪' ),
	array( 'iso' => 'PH', 'name' => 'Philippines', 'dial' => '63', 'flag' => '🇵🇭' ),
	array( 'iso' => 'PN', 'name' => 'Pitcairn', 'dial' => '870', 'flag' => '🇵🇳' ),
	array( 'iso' => 'PL', 'name' => 'Poland', 'dial' => '48', 'flag' => '🇵🇱' ),
	array( 'iso' => 'PT', 'name' => 'Portugal', 'dial' => '351', 'flag' => '🇵🇹' ),
	array( 'iso' => 'PR', 'name' => 'Puerto Rico', 'dial' => '1787', 'flag' => '🇵🇷' ),
	array( 'iso' => 'QA', 'name' => 'Qatar', 'dial' => '974', 'flag' => '🇶🇦' ),
	array( 'iso' => 'RE', 'name' => 'Reunion', 'dial' => '262', 'flag' => '🇷🇪' ),
	array( 'iso' => 'RO', 'name' => 'Romania', 'dial' => '40', 'flag' => '🇷🇴' ),
	array( 'iso' => 'RU', 'name' => 'Russia', 'dial' => '7', 'flag' => '🇷🇺' ),
	array( 'iso' => 'RW', 'name' => 'Rwanda', 'dial' => '250', 'flag' => '🇷🇼' ),
	array( 'iso' => 'BL', 'name' => 'Saint Barthélemy', 'dial' => '590', 'flag' => '🇧🇱' ),
	array( 'iso' => 'SH', 'name' => 'Saint Helena', 'dial' => '290', 'flag' => '🇸🇭' ),
	array( 'iso' => 'KN', 'name' => 'Saint Kitts and Nevis', 'dial' => '1869', 'flag' => '🇰🇳' ),
	array( 'iso' => 'LC', 'name' => 'Saint Lucia', 'dial' => '1758', 'flag' => '🇱🇨' ),
	array( 'iso' => 'SX', 'name' => 'Saint Martin (Dutch part)', 'dial' => '599', 'flag' => '🇸🇽' ),
	array( 'iso' => 'MF', 'name' => 'Saint Martin (French part)', 'dial' => '590', 'flag' => '🇲🇫' ),
	array( 'iso' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'dial' => '508', 'flag' => '🇵🇲' ),
	array( 'iso' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'dial' => '1784', 'flag' => '🇻🇨' ),
	array( 'iso' => 'WS', 'name' => 'Samoa', 'dial' => '685', 'flag' => '🇼🇸' ),
	array( 'iso' => 'SM', 'name' => 'San Marino', 'dial' => '378', 'flag' => '🇸🇲' ),
	array( 'iso' => 'SA', 'name' => 'Saudi Arabia', 'dial' => '966', 'flag' => '🇸🇦' ),
	array( 'iso' => 'SN', 'name' => 'Senegal', 'dial' => '221', 'flag' => '🇸🇳' ),
	array( 'iso' => 'RS', 'name' => 'Serbia', 'dial' => '381', 'flag' => '🇷🇸' ),
	array( 'iso' => 'SC', 'name' => 'Seychelles', 'dial' => '248', 'flag' => '🇸🇨' ),
	array( 'iso' => 'SL', 'name' => 'Sierra Leone', 'dial' => '232', 'flag' => '🇸🇱' ),
	array( 'iso' => 'SG', 'name' => 'Singapore', 'dial' => '65', 'flag' => '🇸🇬' ),
	array( 'iso' => 'SK', 'name' => 'Slovakia', 'dial' => '421', 'flag' => '🇸🇰' ),
	array( 'iso' => 'SI', 'name' => 'Slovenia', 'dial' => '386', 'flag' => '🇸🇮' ),
	array( 'iso' => 'SB', 'name' => 'Solomon Islands', 'dial' => '677', 'flag' => '🇸🇧' ),
	array( 'iso' => 'SO', 'name' => 'Somalia', 'dial' => '252', 'flag' => '🇸🇴' ),
	array( 'iso' => 'ZA', 'name' => 'South Africa', 'dial' => '27', 'flag' => '🇿🇦' ),
	array( 'iso' => 'KR', 'name' => 'South Korea', 'dial' => '82', 'flag' => '🇰🇷' ),
	array( 'iso' => 'SS', 'name' => 'South Sudan', 'dial' => '211', 'flag' => '🇸🇸' ),
	array( 'iso' => 'ES', 'name' => 'Spain', 'dial' => '34', 'flag' => '🇪🇸' ),
	array( 'iso' => 'LK', 'name' => 'Sri Lanka', 'dial' => '94', 'flag' => '🇱🇰' ),
	array( 'iso' => 'SD', 'name' => 'Sudan', 'dial' => '249', 'flag' => '🇸🇩' ),
	array( 'iso' => 'SR', 'name' => 'Suriname', 'dial' => '597', 'flag' => '🇸🇷' ),
	array( 'iso' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 'dial' => '47', 'flag' => '🇸🇯' ),
	array( 'iso' => 'SE', 'name' => 'Sweden', 'dial' => '46', 'flag' => '🇸🇪' ),
	array( 'iso' => 'CH', 'name' => 'Switzerland', 'dial' => '41', 'flag' => '🇨🇭' ),
	array( 'iso' => 'SY', 'name' => 'Syria', 'dial' => '963', 'flag' => '🇸🇾' ),
	array( 'iso' => 'ST', 'name' => 'São Tomé and Príncipe', 'dial' => '239', 'flag' => '🇸🇹' ),
	array( 'iso' => 'TW', 'name' => 'Taiwan', 'dial' => '886', 'flag' => '🇹🇼' ),
	array( 'iso' => 'TJ', 'name' => 'Tajikistan', 'dial' => '992', 'flag' => '🇹🇯' ),
	array( 'iso' => 'TZ', 'name' => 'Tanzania', 'dial' => '255', 'flag' => '🇹🇿' ),
	array( 'iso' => 'TH', 'name' => 'Thailand', 'dial' => '66', 'flag' => '🇹🇭' ),
	array( 'iso' => 'TL', 'name' => 'Timor-Leste', 'dial' => '670', 'flag' => '🇹🇱' ),
	array( 'iso' => 'TG', 'name' => 'Togo', 'dial' => '228', 'flag' => '🇹🇬' ),
	array( 'iso' => 'TK', 'name' => 'Tokelau', 'dial' => '690', 'flag' => '🇹🇰' ),
	array( 'iso' => 'TO', 'name' => 'Tonga', 'dial' => '676', 'flag' => '🇹🇴' ),
	array( 'iso' => 'TT', 'name' => 'Trinidad and Tobago', 'dial' => '1868', 'flag' => '🇹🇹' ),
	array( 'iso' => 'TN', 'name' => 'Tunisia', 'dial' => '216', 'flag' => '🇹🇳' ),
	array( 'iso' => 'TM', 'name' => 'Turkmenistan', 'dial' => '993', 'flag' => '🇹🇲' ),
	array( 'iso' => 'TC', 'name' => 'Turks and Caicos Islands', 'dial' => '1649', 'flag' => '🇹🇨' ),
	array( 'iso' => 'TV', 'name' => 'Tuvalu', 'dial' => '688', 'flag' => '🇹🇻' ),
	array( 'iso' => 'TR', 'name' => 'Türkiye', 'dial' => '90', 'flag' => '🇹🇷' ),
	array( 'iso' => 'UG', 'name' => 'Uganda', 'dial' => '256', 'flag' => '🇺🇬' ),
	array( 'iso' => 'UA', 'name' => 'Ukraine', 'dial' => '380', 'flag' => '🇺🇦' ),
	array( 'iso' => 'AE', 'name' => 'United Arab Emirates', 'dial' => '971', 'flag' => '🇦🇪' ),
	array( 'iso' => 'GB', 'name' => 'United Kingdom (UK)', 'dial' => '44', 'flag' => '🇬🇧' ),
	array( 'iso' => 'US', 'name' => 'United States (US)', 'dial' => '1', 'flag' => '🇺🇸' ),
	array( 'iso' => 'UM', 'name' => 'United States (US) Minor Outlying Islands', 'dial' => '1', 'flag' => '🇺🇲' ),
	array( 'iso' => 'UY', 'name' => 'Uruguay', 'dial' => '598', 'flag' => '🇺🇾' ),
	array( 'iso' => 'UZ', 'name' => 'Uzbekistan', 'dial' => '998', 'flag' => '🇺🇿' ),
	array( 'iso' => 'VU', 'name' => 'Vanuatu', 'dial' => '678', 'flag' => '🇻🇺' ),
	array( 'iso' => 'VA', 'name' => 'Vatican', 'dial' => '379', 'flag' => '🇻🇦' ),
	array( 'iso' => 'VE', 'name' => 'Venezuela', 'dial' => '58', 'flag' => '🇻🇪' ),
	array( 'iso' => 'VN', 'name' => 'Vietnam', 'dial' => '84', 'flag' => '🇻🇳' ),
	array( 'iso' => 'VG', 'name' => 'Virgin Islands (British)', 'dial' => '1284', 'flag' => '🇻🇬' ),
	array( 'iso' => 'VI', 'name' => 'Virgin Islands (US)', 'dial' => '1340', 'flag' => '🇻🇮' ),
	array( 'iso' => 'WF', 'name' => 'Wallis and Futuna', 'dial' => '681', 'flag' => '🇼🇫' ),
	array( 'iso' => 'EH', 'name' => 'Western Sahara', 'dial' => '212', 'flag' => '🇪🇭' ),
	array( 'iso' => 'YE', 'name' => 'Yemen', 'dial' => '967', 'flag' => '🇾🇪' ),
	array( 'iso' => 'ZM', 'name' => 'Zambia', 'dial' => '260', 'flag' => '🇿🇲' ),
	array( 'iso' => 'ZW', 'name' => 'Zimbabwe', 'dial' => '263', 'flag' => '🇿🇼' ),
	array( 'iso' => 'AX', 'name' => 'Åland Islands', 'dial' => '35818', 'flag' => '🇦🇽' ),
);
